# Generated by Django 6.0.3 on 2026-04-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaShop', '0004_alter_teamenumodel_available_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('rating', models.FloatField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_shop', to='teaShop.teashopmodel')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tea', to='teaShop.teamenumodel')),
            ],
        ),
    ]
