# Generated by Django 6.0.3 on 2026-04-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeedbackmodel',
            old_name='tea',
            new_name='flavour',
        ),
    ]
