# Generated by Django 6.0.3 on 2026-04-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_tea_customerfeedbackmodel_flavour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeedbackmodel',
            old_name='flavour',
            new_name='tea',
        ),
    ]
