# Generated by Django 6.0.3 on 2026-04-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_flavour_customerfeedbackmodel_tea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeedbackmodel',
            old_name='tea',
            new_name='flavour',
        ),
    ]
