# Generated by Django 6.0.3 on 2026-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_tea_customerfeedbackmodel_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackmodel',
            name='customer_email',
            field=models.EmailField(default='piyushaawate@gmail.com', max_length=254),
        ),
    ]
