# Generated by Django 6.0.3 on 2026-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_customerfeedbackmodel_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedbackmodel',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
