# Generated by Django 6.0.3 on 2026-04-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField()),
                ('price_per_cup', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TeaShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeaOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='teaShop.teamenumodel')),
            ],
        ),
        migrations.AddField(
            model_name='teamenumodel',
            name='tea_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_shop', to='teaShop.teashopmodel'),
        ),
    ]
