# Generated by Django 6.0.3 on 2026-04-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaordermodel',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_orders', to='teaShop.teamenumodel'),
        ),
        migrations.AlterField(
            model_name='teaordermodel',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
