# Generated by Django 5.2 on 2026-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0002_alter_teaordermodel_tea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamenumodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teaordermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teashopmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
