# Generated by Django 6.0.3 on 2026-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0002_alter_teaordermodel_tea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamenumodel',
            name='flavour',
            field=models.CharField(default='Classic', max_length=100),
        ),
    ]
