# Generated by Django 6.0.3 on 2026-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0003_teamenumodel_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamenumodel',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
