# Generated by Django 6.0.3 on 2026-04-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0004_alter_teamenumodel_available_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='teamenumodel',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_menu', to='teaShop.teaflavour'),
        ),
    ]
