# Generated by Django 6.0.3 on 2026-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0005_teaflavour_alter_teamenumodel_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamenumodel',
            name='flavour',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='TeaFlavour',
        ),
    ]
