# Generated by Django 6.0.3 on 2026-04-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0006_alter_teamenumodel_flavour_delete_teaflavour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaordermodel',
            old_name='tea',
            new_name='flavour',
        ),
    ]
