# Generated by Django 6.0.4 on 2026-04-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0003_alter_teamenumodel_id_alter_teaordermodel_id_and_more'),
        ('teaShop', '0006_alter_teamenumodel_flavour_delete_teaflavour'),
    ]

    operations = [
    ]
