# Generated by Django 6.0.3 on 2026-04-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0007_rename_tea_teaordermodel_flavour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaordermodel',
            old_name='flavour',
            new_name='tea',
        ),
    ]
