# Generated by Django 6.0.3 on 2026-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0008_rename_flavour_teaordermodel_tea'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaordermodel',
            name='customer_email',
            field=models.EmailField(default='piyushaawate@gmail.com', max_length=254),
        ),
    ]
