# Generated by Django 6.0.4 on 2026-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0007_merge_20260415_1730'),
        ('teaShop', '0008_rename_flavour_teaordermodel_tea'),
    ]

    operations = [
    ]
