# Generated by Django 6.0.3 on 2026-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0009_teaordermodel_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaordermodel',
            name='customer_email',
            field=models.EmailField(blank=True, default='piyushaawate@gmail.com', max_length=254, null=True),
        ),
    ]
