# Generated by Django 6.0.4 on 2026-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0011_alter_teaordermodel_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaordermodel',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
