# Generated by Django 6.0.4 on 2026-04-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaShop', '0010_alter_teamenumodel_id_alter_teaordermodel_id_and_more'),
        ('teaShop', '0011_alter_teaordermodel_customer_email'),
    ]

    operations = [
    ]
